---
version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Europe/London"
    versioning-strategy: increase
    groups:
      dev-dependencies:
        dependency-type: "development"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "08:00"
      timezone: "Europe/London"
