require:
  - rubocop-performance
  - rubocop-rake

AllCops:
  DisplayStyleGuide: true
  NewCops: enable

# Require versions for every gem
Bundler/GemVersion:
  Enabled: true

Gemspec/DependencyVersion:
  Enabled: true

Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: same_line

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

# Allow short parameter names (e.g. coords(x, y))
Naming/MethodParameterName:
  MinNameLength: 1

# Double quotes everywhere so they don't have to change if interpolation is added to a string
Style/StringLiterals:
  EnforcedStyle: double_quotes
