require:
  - rubocop-rails
  - rubocop-rails-accessibility

AllCops:
  ActiveSupportExtensionsEnabled: true

# Config blocks can be very long
Metrics/BlockLength:
  Exclude:
    - 'config/**/*'

# casecmp does not work with all of Unicode, so this is not a good optimization for internationalized apps
Performance/Casecmp:
  Enabled: false

# This cop is unsafe because it has known compatibility issues with ActiveRecord and other frameworks.
Performance/Count:
  Enabled: false

# This cop is unsafe because it has known compatibility issues with ActiveRecord and other frameworks.
Performance/Detect:
  Enabled: false

# Sum is different between enumerables and ActiveRecord, let's not cause confusion...
Performance/Sum:
  Enabled: false

Rails/DefaultScope:
  Enabled: true

Rails/EnvironmentVariableAccess:
  Enabled: true

Rails/OrderById:
  Enabled: true

Rails/PluckId:
  Enabled: true

Rails/TableNameAssignment:
  Enabled: true

Style/Documentation:
  Exclude:
    - app/controllers/**/*
    - app/mailers/**/*
    - app/models/**/*
    - config/**/*
    - db/migrate/**/*
    - test/**/*
